### ISSUE TITLE
Encountered warning:TF_REPEATED_DATA run RNE in Neotic

### ISSUE THREAD

**Issue by 1messy1** [MarcoStb1993/rnexploration#4]
Hi, when i run RNE in Neotic i encounted the warning : "TF_REPEATED_DATA ignoring data with redundant timestamp for frame base_footprint at time 61.723000 according to authority unknown_publisher". Although it does not affect the operation of the program, I would like to know what the problem is. It may be a version problem. Do you have any ideas to solve this problem?

**Comment by MarcoStb1993** [comment]
Hey, this seems to be a problem with Noetic and the geometry package rather than this package according to this [ROS answers thread](https://answers.ros.org/question/359968/tf_repeated_data-error-with-robot_localization-ukf-package/?answer=359976#post-id-359976).  
Further discussion can also be found [here](https://github.com/ros/geometry2/issues/467).  

So, I would say, nothing to worry about. :)
